[changelog]
header = ""
body = """
## [{{ version }}](https://github.com/carbon-design-system/carbon-echarts-theme/releases/tag/{{ version }}) ({{ timestamp | date(format="%Y-%m-%d") }})

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ commit.message }} ([`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/carbon-design-system/carbon-echarts-theme/commit/{{ commit.id }}))
{%- endfor %}
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactoring" },
  { message = "^docs", group = "Documentation" },
  { message = "^test", group = "Tests" },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^chore", group = "Chores" },
  { message = "^style", group = "Styling" },
  { message = "^ci", group = "CI/CD" },
]
filter_commits = true
tag_pattern = "v[0-9].*"
sort_commits = "newest"
